### ISSUE TITLE
Is there any installation guidance? 

### ISSUE THREAD

**Issue by Kiteretsu77** [yangxy/PASD#11]
Hello! Is there any package installation guidance? I try to use pip install -r requirements.txt. However, the diffusers package with the latest one cannot find some function sometimes. Is there any specific version for diffusers used in the experiments of the paper? Thanks!

**Comment by yangxy** [comment]
I have updated the project to support the latest diffusers(=0.21.4). Please have a try now.

**Comment by h3clikejava** [comment]
(h3c_temp) h3c@H3c-4070:~/Documents/PASD$ python gradio_pasd.py
/home/h3c/Documents/PASD/pipelines/pipeline_pasd.py:41: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
/home/h3c/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/h3c/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
/home/h3c/.local/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/home/h3c/Documents/PASD/gradio_pasd.py", line 41, in <module>
    text_encoder = CLIPTextModel.from_pretrained(pretrained_model_path, subfolder="text_encoder")
  File "/home/h3c/anaconda3/envs/h3c_temp/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/h3c/anaconda3/envs/h3c_temp/lib/python3.10/site-packages/transformers/modeling_utils.py", line 402, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
