### ISSUE TITLE
ImportError: cannot import name 'PositionNet'

### ISSUE THREAD

**Issue by AIisCool** [yangxy/PASD#13]
```
C:\PASD-main>python gradio_pasd.py
C:\PASD-main\pipelines\pipeline_pasd.py:42: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
C:\Python310\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Python310\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "C:\PASD-main\gradio_pasd.py", line 29, in <module>
    from models.pasd.unet_2d_condition import UNet2DConditionModel
  File "C:\PASD-main\models\pasd\unet_2d_condition.py", line 27, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (C:\Python310\lib\site-packages\diffusers\models\embeddings.py)
```

**Comment by chky** [comment]
I met the same problem when I used diffusers=0.19, but the error disappeared when I changed to diffusers=0.21
