### ISSUE TITLE
ImportError: cannot import name 'is_compiled_module' from 'diffusers.utils'

### ISSUE THREAD

**Issue by AIisCool** [yangxy/PASD#14]
```
python test_pasd.py
Traceback (most recent call last):
  File "C:\PASD-main\test_pasd.py", line 22, in <module>
    from pipelines.pipeline_pasd import StableDiffusionControlNetPipeline
  File "C:\PASD-main\pipelines\pipeline_pasd.py", line 32, in <module>
    from diffusers.utils import (
ImportError: cannot import name 'is_compiled_module' from 'diffusers.utils' (C:\Python310\lib\site-packages\diffusers\utils\__init__.py)
```

```
$ python test_pasd.py
Traceback (most recent call last):
  File "C:\PASD-main\test_pasd.py", line 22, in <module>
    from pipelines.pipeline_pasd import StableDiffusionControlNetPipeline
  File "C:\PASD-main\pipelines\pipeline_pasd.py", line 32, in <module>
    from diffusers.utils import (
ImportError: cannot import name 'randn_tensor' from 'diffusers.utils' (C:\Python310\lib\site-packages\diffusers\utils\__init__.py)
```

```
 python test_pasd.py
C:\PASD-main\pipelines\pipeline_pasd.py:45: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
C:\Python310\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "C:\PASD-main\test_pasd.py", line 267, in <module>
    main(args)
  File "C:\PASD-main\test_pasd.py", line 167, in main
    pipeline = load_pasd_pipeline(args, accelerator, enable_xformers_memory_efficient_attention)
  File "C:\PASD-main\test_pasd.py", line 40, in load_pasd_pipeline
    from models.pasd.controlnet import ControlNetModel
  File "C:\PASD-main\models\pasd\controlnet.py", line 27, in <module>
    from basicsr.archs.rrdbnet_arch import RRDB
ModuleNotFoundError: No module named 'basicsr.archs.rrdbnet_arch'
```

**Comment by yangxy** [comment]
Please use diffusers=0.21.4, and install basicsr correctly.

**Comment by AIisCool** [comment]
@yangxy Yes I managed to fix those errors but now I get this:

```
$ python test_pasd.py
C:\PASD-main\pipelines\pipeline_pasd.py:45: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
C:\Python310\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "C:\PASD-main\test_pasd.py", line 267, in <module>
    main(args)
  File "C:\PASD-main\test_pasd.py", line 167, in main
    pipeline = load_pasd_pipeline(args, accelerator, enable_xformers_memory_efficient_attention)
  File "C:\PASD-main\test_pasd.py", line 45, in load_pasd_pipeline
    vae = AutoencoderKL.from_pretrained(args.pretrained_model_path, subfolder="vae")
  File "C:\Python310\lib\site-packages\diffusers\models\modeling_utils.py", line 646, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'> from checkpoints/stable-diffusion-v1-5 because the following keys are missing:
 encoder.mid_block.attentions.0.to_out.0.bias, decoder.up_blocks.1.resnets.2.conv2.weight, decoder.up_blocks.2.resnets.2.conv1.bias, decoder.conv_in.bias, decoder.mid_block.attentions.0.group_norm.weight, encoder.down_blocks.2.resnets.0.conv_shortcut.weight, encoder.down_blocks.3.resnets.0.conv1.bias, encoder.mid_block.resnets.1.conv1.bias, decoder.up_blocks.2.resnets.0.conv2.weight, encoder.down_blocks.1.resnets.0.norm1.weight, decoder.up_blocks.1.resnets.1.conv1.weight, decoder.up_blocks.0.resnets.1.conv1.bias, decoder.up_blocks.2.resnets.0.conv1.weight, encoder.mid_block.attentions.0.to_v.bias, decoder.up_blocks.3.resnets.0.norm1.bias, decoder.up_blocks.0.resnets.2.norm2.bias, encoder.down_blocks.3.resnets.1.norm2.weight, encoder.down_blocks.2.resnets.0.conv_shortcut.bias, decoder.up_blocks.3.resnets.1.norm2.weight, decoder.up_blocks.0.resnets.1.norm1.bias, decoder.up_blocks.3.resnets.0.conv1.bias, decoder.up_blocks.1.resnets.0.norm1.bias, encoder.down_blocks.1.resnets.1.norm2.weight, decoder.up_blocks.0.resnets.0.norm1.weight, decoder.up_blocks.3.resnets.2.conv2.weight, encoder.mid_block.resnets.0.norm1.weight, encoder.down_blocks.3.resnets.0.conv1.weight, encoder.conv_in.weight, encoder.down_blocks.1.resnets.0.conv2.weight, encoder.down_blocks.2.resnets.0.norm1.weight, encoder.down_blocks.0.resnets.1.conv1.bias, encoder.mid_block.resnets.0.norm2.bias, decoder.up_blocks.1.resnets.1.norm1.weight, decoder.up_blocks.3.resnets.0.norm2.weight, encoder.down_blocks.0.resnets.1.norm2.weight, decoder.up_blocks.3.resnets.0.conv_shortcut.weight, encoder.down_blocks.3.resnets.1.conv1.bias, encoder.down_blocks.3.resnets.1.norm1.weight, decoder.up_blocks.1.resnets.0.conv2.bias, decoder.up_blocks.0.resnets.1.norm2.bias, decoder.up_blocks.3.resnets.2.norm2.bias, decoder.up_blocks.2.resnets.1.norm1.bias, decoder.up_blocks.2.resnets.0.conv_shortcut.bias, decoder.up_blocks.1.resnets.0.norm2.weight, encoder.down_blocks.0.resnets.1.conv2.bias, decoder.up_blocks.2.resnets.1.norm2.bias, encoder.mid_block.attentions.0.group_norm.weight, decoder.up_blocks.0.resnets.0.conv2.weight, decoder.up_blocks.0.resnets.1.conv1.weight, encoder.conv_norm_out.bias, decoder.mid_block.resnets.1.norm1.bias, decoder.up_blocks.3.resnets.2.conv2.bias, encoder.mid_block.resnets.0.conv2.weight, encoder.mid_block.resnets.1.conv2.bias, decoder.mid_block.resnets.1.conv2.weight, decoder.up_blocks.2.resnets.0.norm1.bias, decoder.up_blocks.2.resnets.2.conv2.weight, decoder.mid_block.resnets.0.norm2.weight, decoder.up_blocks.2.resnets.0.conv1.bias, decoder.mid_block.attentions.0.to_q.bias, decoder.up_blocks.1.resnets.1.conv1.bias, encoder.down_blocks.1.resnets.0.conv1.bias, encoder.down_blocks.2.resnets.1.norm2.weight, encoder.down_blocks.0.resnets.0.norm2.bias, decoder.up_blocks.1.resnets.2.norm1.bias, decoder.up_blocks.0.resnets.1.conv2.weight, decoder.up_blocks.2.resnets.1.conv2.bias, encoder.down_blocks.3.resnets.0.norm2.bias, encoder.down_blocks.2.resnets.0.norm2.weight, encoder.down_blocks.1.resnets.1.conv1.weight, encoder.down_blocks.2.resnets.0.conv2.weight, encoder.down_blocks.2.resnets.0.conv1.bias, decoder.up_blocks.3.resnets.2.conv1.weight, encoder.conv_norm_out.weight, decoder.up_blocks.3.resnets.0.conv2.bias, decoder.mid_block.resnets.1.norm2.bias, decoder.up_blocks.2.resnets.0.norm1.weight, encoder.down_blocks.2.resnets.1.conv1.bias, decoder.mid_block.resnets.0.conv1.weight, decoder.mid_block.attentions.0.group_norm.bias, decoder.up_blocks.0.upsamplers.0.conv.weight, decoder.mid_block.attentions.0.to_q.weight, encoder.down_blocks.2.resnets.1.norm1.bias, encoder.conv_out.bias, decoder.up_blocks.0.resnets.2.norm1.weight, decoder.mid_block.resnets.1.norm1.weight, encoder.down_blocks.1.resnets.0.conv2.bias, decoder.up_blocks.0.resnets.0.norm2.weight, decoder.up_blocks.2.resnets.2.norm1.bias, decoder.mid_block.attentions.0.to_v.bias, encoder.down_blocks.0.resnets.0.conv2.bias, decoder.up_blocks.0.resnets.2.conv2.weight, decoder.mid_block.resnets.1.conv1.bias, encoder.down_blocks.2.resnets.1.conv1.weight, encoder.mid_block.attentions.0.to_q.weight, encoder.mid_block.resnets.1.conv2.weight, encoder.down_blocks.2.resnets.0.norm2.bias, decoder.up_blocks.2.resnets.0.conv_shortcut.weight, decoder.up_blocks.3.resnets.2.norm1.weight, encoder.down_blocks.2.resnets.0.norm1.bias, encoder.down_blocks.1.resnets.1.conv2.bias, encoder.down_blocks.0.resnets.1.norm1.weight, encoder.down_blocks.3.resnets.0.conv2.weight, decoder.up_blocks.0.resnets.0.conv1.weight, decoder.up_blocks.2.resnets.0.conv2.bias, decoder.up_blocks.2.resnets.1.norm2.weight, decoder.up_blocks.3.resnets.2.norm1.bias, decoder.mid_block.resnets.0.conv1.bias, encoder.down_blocks.0.resnets.0.conv2.weight, encoder.down_blocks.2.resnets.1.norm2.bias, decoder.up_blocks.2.resnets.1.norm1.weight, encoder.mid_block.resnets.0.conv1.weight, decoder.up_blocks.3.resnets.0.conv1.weight, encoder.down_blocks.0.resnets.1.norm1.bias, decoder.mid_block.resnets.0.norm1.bias, encoder.mid_block.resnets.1.norm1.bias, post_quant_conv.bias, decoder.up_blocks.2.resnets.1.conv1.weight, encoder.down_blocks.3.resnets.1.conv2.weight, decoder.conv_norm_out.bias, decoder.up_blocks.0.resnets.0.conv2.bias, decoder.up_blocks.1.upsamplers.0.conv.weight, decoder.up_blocks.0.upsamplers.0.conv.bias, decoder.up_blocks.3.resnets.1.conv2.bias, encoder.down_blocks.1.resnets.1.norm1.weight, decoder.up_blocks.2.resnets.2.conv2.bias, encoder.down_blocks.2.resnets.0.conv2.bias, decoder.up_blocks.3.resnets.1.conv1.weight, decoder.up_blocks.3.resnets.1.norm1.bias, encoder.down_blocks.0.resnets.1.norm2.bias, encoder.down_blocks.3.resnets.0.norm2.weight, decoder.mid_block.attentions.0.to_out.0.bias, decoder.up_blocks.1.resnets.1.norm2.bias, encoder.mid_block.attentions.0.to_out.0.weight, decoder.up_blocks.1.resnets.1.conv2.bias, decoder.mid_block.resnets.0.norm2.bias, encoder.down_blocks.1.resnets.0.conv_shortcut.bias, encoder.down_blocks.0.downsamplers.0.conv.bias, decoder.up_blocks.0.resnets.1.norm1.weight, post_quant_conv.weight, decoder.up_blocks.2.resnets.2.conv1.weight, encoder.mid_block.attentions.0.to_q.bias, decoder.up_blocks.1.resnets.0.norm1.weight, decoder.up_blocks.0.resnets.0.norm2.bias, decoder.up_blocks.1.resnets.2.norm2.bias, decoder.mid_block.resnets.0.conv2.bias, decoder.up_blocks.1.resnets.1.norm1.bias, decoder.mid_block.attentions.0.to_k.weight, encoder.down_blocks.3.resnets.0.norm1.weight, encoder.mid_block.attentions.0.to_k.bias, encoder.down_blocks.1.downsamplers.0.conv.bias, encoder.conv_out.weight, encoder.down_blocks.0.resnets.1.conv2.weight, decoder.up_blocks.1.resnets.0.conv1.bias, encoder.down_blocks.3.resnets.0.conv2.bias, encoder.mid_block.resnets.1.conv1.weight, decoder.up_blocks.1.resnets.2.norm2.weight, encoder.down_blocks.1.resnets.0.conv1.weight, decoder.up_blocks.1.resnets.0.conv1.weight, encoder.down_blocks.3.resnets.1.norm2.bias, decoder.up_blocks.1.resnets.2.conv1.bias, decoder.up_blocks.0.resnets.2.norm1.bias, decoder.conv_in.weight, decoder.mid_block.resnets.1.conv1.weight, encoder.down_blocks.0.resnets.0.conv1.bias, decoder.up_blocks.0.resnets.1.norm2.weight, decoder.conv_norm_out.weight, decoder.mid_block.attentions.0.to_out.0.weight, encoder.down_blocks.1.resnets.0.norm2.bias, decoder.up_blocks.2.resnets.1.conv2.weight, encoder.down_blocks.3.resnets.0.norm1.bias, decoder.up_blocks.0.resnets.2.conv1.bias, encoder.down_blocks.2.resnets.1.conv2.weight, decoder.mid_block.resnets.1.conv2.bias, encoder.down_blocks.1.resnets.1.conv2.weight, decoder.conv_out.bias, quant_conv.weight, encoder.down_blocks.1.resnets.0.norm2.weight, encoder.mid_block.resnets.0.conv1.bias, decoder.up_blocks.1.resnets.2.norm1.weight, encoder.down_blocks.3.resnets.1.norm1.bias, decoder.up_blocks.3.resnets.2.conv1.bias, encoder.mid_block.resnets.1.norm1.weight, decoder.up_blocks.0.resnets.2.conv2.bias, encoder.down_blocks.1.downsamplers.0.conv.weight, decoder.mid_block.resnets.0.conv2.weight, encoder.down_blocks.2.downsamplers.0.conv.weight, encoder.down_blocks.1.resnets.1.conv1.bias, decoder.mid_block.attentions.0.to_k.bias, quant_conv.bias, decoder.up_blocks.0.resnets.2.conv1.weight, encoder.mid_block.resnets.0.conv2.bias, decoder.up_blocks.3.resnets.0.norm1.weight, encoder.down_blocks.0.resnets.0.conv1.weight, decoder.up_blocks.3.resnets.1.conv1.bias, encoder.mid_block.attentions.0.to_v.weight, encoder.down_blocks.1.resnets.1.norm1.bias, decoder.mid_block.attentions.0.to_v.weight, decoder.up_blocks.3.resnets.0.conv_shortcut.bias, decoder.up_blocks.2.resnets.2.norm1.weight, decoder.up_blocks.0.resnets.0.conv1.bias, decoder.up_blocks.1.resnets.1.norm2.weight, decoder.up_blocks.2.upsamplers.0.conv.weight, decoder.up_blocks.3.resnets.0.conv2.weight, encoder.down_blocks.1.resnets.0.norm1.bias, decoder.up_blocks.3.resnets.1.norm1.weight, encoder.down_blocks.2.resnets.1.conv2.bias, encoder.down_blocks.0.resnets.0.norm2.weight, encoder.conv_in.bias, encoder.down_blocks.0.downsamplers.0.conv.weight, encoder.mid_block.resnets.0.norm1.bias, decoder.up_blocks.0.resnets.2.norm2.weight, decoder.up_blocks.3.resnets.2.norm2.weight, decoder.up_blocks.3.resnets.1.norm2.bias, encoder.down_blocks.0.resnets.1.conv1.weight, encoder.down_blocks.1.resnets.0.conv_shortcut.weight, decoder.up_blocks.1.upsamplers.0.conv.bias, decoder.up_blocks.2.resnets.2.norm2.weight, encoder.mid_block.resnets.1.norm2.weight, decoder.up_blocks.0.resnets.1.conv2.bias, encoder.down_blocks.3.resnets.1.conv1.weight, encoder.down_blocks.2.resnets.1.norm1.weight, encoder.mid_block.resnets.0.norm2.weight, decoder.up_blocks.2.resnets.1.conv1.bias, encoder.down_blocks.2.downsamplers.0.conv.bias, decoder.up_blocks.3.resnets.1.conv2.weight, decoder.up_blocks.3.resnets.0.norm2.bias, decoder.up_blocks.2.resnets.0.norm2.weight, encoder.down_blocks.0.resnets.0.norm1.bias, encoder.down_blocks.2.resnets.0.conv1.weight, decoder.up_blocks.1.resnets.2.conv1.weight, decoder.mid_block.resnets.0.norm1.weight, encoder.down_blocks.3.resnets.1.conv2.bias, decoder.up_blocks.2.resnets.2.norm2.bias, decoder.mid_block.resnets.1.norm2.weight, encoder.down_blocks.0.resnets.0.norm1.weight, encoder.mid_block.attentions.0.to_k.weight, decoder.up_blocks.2.resnets.0.norm2.bias, decoder.up_blocks.1.resnets.1.conv2.weight, encoder.mid_block.attentions.0.group_norm.bias, decoder.up_blocks.2.upsamplers.0.conv.bias, decoder.up_blocks.1.resnets.0.conv2.weight, decoder.conv_out.weight, encoder.down_blocks.1.resnets.1.norm2.bias, decoder.up_blocks.0.resnets.0.norm1.bias, encoder.mid_block.resnets.1.norm2.bias, decoder.up_blocks.1.resnets.0.norm2.bias, decoder.up_blocks.1.resnets.2.conv2.bias.
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
```


I downloaded the v1-5-pruned.ckpt and put it into the .\checkpoints\stable-diffusion-v1-5 folder.

**Comment by yangxy** [comment]
You should download the whole repo of stabe-diffusion-v1-5 from huggingface via "git lfs clone https:XXXX" including all the subfolders and bin files.
Those .ckpt files are not used in this repo.
