### ISSUE TITLE
PASD-SDXL RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by AIisCool** [yangxy/PASD#63]
```
python test_pasd_sdxl.py
The config attributes {'use_sd3_vae': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
The config attributes {'use_sd3_vae': False} were passed to ControlNetModel, but are not expected and will be ignored. Please verify your config.json configuration file.
INFO:root:Loaded coca_ViT-L-14 model config.
INFO:root:Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
Traceback (most recent call last):
  File "C:\PASD\test_pasd_sdxl.py", line 316, in <module>
    main(args)
  File "C:\PASD\test_pasd_sdxl.py", line 226, in main
    validation_prompt = get_validation_prompt(args, validation_image, model, preprocess, category)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PASD\test_pasd_sdxl.py", line 176, in get_validation_prompt
    generated = model.generate(image)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\open_clip\coca_model.py", line 233, in generate
    output = self._generate_beamsearch(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\open_clip\coca_model.py", line 442, in _generate_beamsearch
    if beam_scorer.is_done or stopping_criteria(input_ids, None):
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

I'm not sure what is wrong or how to fix it?

Was attempting to test with this image:
![304-the-swarm-204](https://github.com/user-attachments/assets/c9f4dc2c-046d-4099-bbc4-ea8ff1461067)

**Comment by zelenooki87** [comment]
@AIisCool 
For me code working but results are far from expected. Osediff does better job.

**Comment by yangxy** [comment]
> ```
> python test_pasd_sdxl.py
> The config attributes {'use_sd3_vae': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
> The config attributes {'use_sd3_vae': False} were passed to ControlNetModel, but are not expected and will be ignored. Please verify your config.json configuration file.
> INFO:root:Loaded coca_ViT-L-14 model config.
> INFO:root:Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
> Traceback (most recent call last):
>   File "C:\PASD\test_pasd_sdxl.py", line 316, in <module>
>     main(args)
>   File "C:\PASD\test_pasd_sdxl.py", line 226, in main
>     validation_prompt = get_validation_prompt(args, validation_image, model, preprocess, category)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\PASD\test_pasd_sdxl.py", line 176, in get_validation_prompt
>     generated = model.generate(image)
>                 ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\open_clip\coca_model.py", line 233, in generate
>     output = self._generate_beamsearch(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\open_clip\coca_model.py", line 442, in _generate_beamsearch
>     if beam_scorer.is_done or stopping_criteria(input_ids, None):
> RuntimeError: Boolean value of Tensor with more than one value is ambiguous
> ```
> 
> I'm not sure what is wrong or how to fix it?
> 
> Was attempting to test with this image: ![304-the-swarm-204](https://private-user-images.githubusercontent.com/92149242/364332506-c9f4dc2c-046d-4099-bbc4-ea8ff1461067.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDk5NzcsIm5iZiI6MTcyNTQ0OTY3NywicGF0aCI6Ii85MjE0OTI0Mi8zNjQzMzI1MDYtYzlmNGRjMmMtMDQ2ZC00MDk5LWJiYzQtZWE4ZmYxNDYxMDY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMDlkMDkzYTk4Njc2OWExMGNkNTEyZGY4MGYzOGJkMTZkMjExNWVmOWY3ZGQyMTEyNDM3NDY0MDlkZDgyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tTs_U6PK6WJdiInak5caeJgL4JPMdwCYp6Eq5mOM0Oo)

My fault. I have updated the huggingface repo. Please install the latest ```open_clip_torch```.

**Comment by yangxy** [comment]
> @AIisCool For me code working but results are far from expected. Osediff does better job.(and lot fasster) <img alt="Skrinšot-000007" width="1280" src="https://private-user-images.githubusercontent.com/75204635/364340880-17d05293-a2b9-42a5-9205-7ca48b9de364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDk5NzcsIm5iZiI6MTcyNTQ0OTY3NywicGF0aCI6Ii83NTIwNDYzNS8zNjQzNDA4ODAtMTdkMDUyOTMtYTJiOS00MmE1LTkyMDUtN2NhNDhiOWRlMzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NmFiODc0NWU4NzdhZDg0ZTFkMGY5YTVlMzI1ODAwM2FhMzM1NmQ5ZTFkNzZhZGY1NGJkZWYyZTBlY2ExNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PUb1PBTN9by_jxhcjAb7AsvddhQV0FDVhbe49BIX6o"> <img alt="Skrinšot-000008" width="1280" src="https://private-user-images.githubusercontent.com/75204635/364340887-1bc90a83-aff5-4216-82e4-c71a9cffc854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDk5NzcsIm5iZiI6MTcyNTQ0OTY3NywicGF0aCI6Ii83NTIwNDYzNS8zNjQzNDA4ODctMWJjOTBhODMtYWZmNS00MjE2LTgyZTQtYzcxYTljZmZjODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODZjNTYxYTVkMGI2MDQzZWQ5NWNlZjE3ZGMzMGU4NjA2NjFmMzQ4NGMyZTRiNzY5MzFkNTYzODE1YjJiODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DIlTjB7r89Y6gWfZ8ZSxleOiLVSQLWWHB4Xu_rMmkrY"> <img alt="Skrinšot-000009" width="1280" src="https://private-user-images.githubusercontent.com/75204635/364340888-5b74020f-da23-4268-a2ea-ce4f435d3973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDk5NzcsIm5iZiI6MTcyNTQ0OTY3NywicGF0aCI6Ii83NTIwNDYzNS8zNjQzNDA4ODgtNWI3NDAyMGYtZGEyMy00MjY4LWEyZWEtY2U0ZjQzNWQzOTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNTk5Y2YwMjI3ZWI0Nzk5NjhhMWUzZjU3NzAxMmI3NWE5OTA0NmM0MjMzMDA3MzkyZjk2NWM0MWE5Y2NkMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BtGwrqWM017BiSyEHG5ujw7ON3huigGZkiXKoQfeWeg">

Thanks for your interest. I would recommend to increase the values of ```--upscale``` or ```--process_size``` for better results. You can also try to tune a proprer ```--guidance_scale``` and ```--conditioning_scale```.

**Comment by yangxy** [comment]
I had focused to make the generated results of PASD-SDXL more **photorealistic**. Unfortunately, the results may not that clean or sharp in many cases as that is not my primary purpose.

**Comment by AIisCool** [comment]
> My fault. I have updated the huggingface repo. Please install the latest `open_clip_torch`.

Thanks that fixed it.

**Comment by AIisCool** [comment]
@yangxy Is there any way that I can get it to better recognize these as circles and not squares?

![image](https://github.com/user-attachments/assets/d2803025-46c3-406a-9f9f-c73963989f5b)

![image](https://github.com/user-attachments/assets/2e0924e9-a948-427e-af43-f0c877bd4283)

**Comment by yangxy** [comment]
> @yangxy Is there any way that I can get it to better recognize these as circles and not squares?
> 
> ![image](https://private-user-images.githubusercontent.com/92149242/364700346-d2803025-46c3-406a-9f9f-c73963989f5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzM5NDYsIm5iZiI6MTcyNTYzMzY0NiwicGF0aCI6Ii85MjE0OTI0Mi8zNjQ3MDAzNDYtZDI4MDMwMjUtNDZjMy00MDZhLTlmOWYtYzczOTYzOTg5ZjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0NDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwM2U1NzI5ZTZiOTExMDc2YzVlMjdlMDY2YmJhODE1OWQyNzM4MGIzNDc1MWU5ZTllNzU0MDIyMTMxZjdjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1fOhjpDT5UnjAUQ4G4UP3bClih-gCUnsPLLZOolq3K8)
> 
> ![image](https://private-user-images.githubusercontent.com/92149242/364700421-2e0924e9-a948-427e-af43-f0c877bd4283.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzM5NDYsIm5iZiI6MTcyNTYzMzY0NiwicGF0aCI6Ii85MjE0OTI0Mi8zNjQ3MDA0MjEtMmUwOTI0ZTktYTk0OC00MjdlLWFmNDMtZjBjODc3YmQ0MjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0NDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MTIzY2ViYmZlODI1Yjk0MTAxMzNmMjdkMzAwMTVlNjQ0MzUwZDQ3Y2ZjZWRlM2IwMTE4N2MyMmI4ZmEzNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Odx3QrDY5XUZN514BgTexhT88ahnhywp9UBmPy2bMk)

You can try to reduce ``--guidance_scale``, increase ``--conditioning_scale``, and adjust ``--process_size ``. You can also try to add "circles" to the text prompt. The negative prompt (that I used during training) is also adjustable.

**Comment by AIisCool** [comment]
> You can try to reduce `--guidance_scale`, increase `--conditioning_scale`, and adjust `--process_size `. You can also try to add "circles" to the text prompt. The negative prompt (that I used during training) is also adjustable.

Hm I have tried those, but no matter what, it will not generate circles.

**Comment by AIisCool** [comment]
@yangxy unrelated to the previous question, I wonder as someone who created this restoration for images, do you think stable diffusion will ever be able to process a video and not change the content with each frame? That it will be able to process/"understand" the data as a sequence rather than individual images?

**Comment by yangxy** [comment]
> @yangxy unrelated to the previous question, I wonder as someone who created this restoration for images, do you think stable diffusion will ever be able to process a video and not change the content with each frame? That it will be able to process/"understand" the data as a sequence rather than individual images? Also perhaps one day it will better understand/identify the low-resolution objects on the input image/video and better replicate them?

You mean VSR? I am working on it, but still far from perfect. Maybe we need a good text2video pretrain.

**Comment by AIisCool** [comment]
> You mean VSR? I am working on it, but still far from perfect.

Yes! The restoration results I've seen from PASD and SeeSR far surpass any commercial product like Topaz Photo AI or Topaz Video AI. If it was configured for video, it would be truly amazing to see the results be temporally stable.

**Comment by zelenooki87** [comment]
> > You mean VSR? I am working on it, but still far from perfect.
> 
> Yes! The restoration results I've seen from PASD and SeeSR far surpass any commercial product like Topaz Photo AI or Topaz Video AI. If it was configured for video, it would be truly amazing to see the results be temporally stable.

My friend, try this project, it is based on Osediff but much more realistic results. I was not able to run it on Windows. At Ubuntu everyithing goes well.
https://github.com/ArcticHare105/S3Diff
Greetz

**Comment by xiaoli1996** [comment]
Thanks for your reply!
