### ISSUE TITLE
TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hooks'

### ISSUE THREAD

**Issue by RC-Hong** [yangxy/PASD#67]
Run python test_pasd_sdxl.py
Traceback (most recent call last):
  File "D:\PASD\test_pasd_sdxl.py", line 319, in <module>
    main(args)
  File "D:\PASD\test_pasd_sdxl.py", line 206, in main
    pipeline, refiner_pipeline = load_pasd_pipeline(args, accelerator, enable_xformers_memory_efficient_attention)
  File "D:\PASD\test_pasd_sdxl.py", line 59, in load_pasd_pipeline
    unet = UNet2DConditionModel.from_pretrained(f"{args.pasd_model_path}/unet")
  File "D:\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\python\lib\site-packages\diffusers\models\modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hooks'
#=============================#
And edit gradio_pasd.py to 
pretrained_model_path = "checkpoints/stable-diffusion-xl-base-1.0"  #stable-diffusion-v1-5"
ckpt_path = "runs/pasd_sdxl/checkpoint-200000"            #pasd/checkpoint-100000"
dreambooth_lora_path = "checkpoints/personalized_models/sdxl_lcm_lora.safetensors"     #majicmixRealistic_v6.safetensors"
#feature_extractor = CLIPImageProcessor.from_pretrained(f"{pretrained_model_path}/feature_extractor")

Run python gradio_pasd.py
D:\python\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\python\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "D:\PASD\gradio_pasd.py", line 43, in <module>
    unet = UNet2DConditionModel.from_pretrained(ckpt_path, subfolder="unet")
  File "D:\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\python\lib\site-packages\diffusers\models\modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hooks'

**Comment by yangxy** [comment]
Update diffusers to the latest version.

**Comment by yangxy** [comment]
Update accelerate to the latest version.
